name: CI
on:
  push:
    branches:
      - main
      - release-*
      - runci/*
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8'
          - 'nightly'
        os:
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          show-versioninfo: true
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
      - name: Submit coverage to Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info

  docs:
    name: 'Documentation: ${{ matrix.format }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        format:
          - html
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: julia --color=yes --project=docs/ docs/instantiate.jl
      - name: Build the manual
        run: julia --color=yes --project=docs/ docs/make.jl ${{ matrix.format }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}

  changelog:
    name: "Verify CHANGELOG"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.8'
      - name: Install dependencies
        run: julia --color=yes --project=scripts/ -e 'using Pkg; Pkg.instantiate()'
      - name: Test scripts/changelog.jl
        run: |
          # Run the unit tests of the changelog.jl script:
          julia --color=yes --code-coverage --project=scripts/ scripts/changelog.jl test
          # Run changelog.jl with a small, but known good CHANGELOG file and make sure it passes:
          julia --color=yes --code-coverage --project=scripts/ scripts/changelog.jl --file=scripts/changelog-valid.md
          # Run changelog.jl with a known _bad_ CHANGELOG file, which should exit with a non-zero code:
          ! julia --color=yes --code-coverage --project=scripts/ scripts/changelog.jl --file=scripts/changelog-invalid.md
      - name: Check CHANGELOG.md
        run: julia --color=yes --code-coverage --project=scripts/ scripts/changelog.jl --github
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,scripts
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
      - name: Submit coverage to Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
